language: node_js

sudo: false

branches:
  only:
  - main
  - /.*/

node_js:
- 16
- 18

script:
- npm run build
- npm run test-travis || travis_terminate 1
- npm run lint
- npm run check-packages
# - sh scripts/typedoc/generate_typedoc.sh currently in progress


deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 16
    branch: main
